apiVersion: stork.libopenstorage.org/v1alpha1
kind: Migration
metadata:
  name: migrate-bbq-bookkeeper
  namespace: portworx
spec:
  clusterPair: demo
  includeResources: false
  startApplications: false
  namespaces:
    - bbq-bookkeeper
  purgeDeletedResources: false
  # selectors: 
  #   pxmigrate: "true"
