apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stage-bbqbookkeeper-argo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: in-cluster
  project: "15021935"
  source:
    path: argo-bbq-bookkeeper/apps/bbq-bookkeeper
    repoURL: https://github.com/ccrow42/px-bookkeeper-database-change-demo.git
    targetRevision: HEAD